[ ca ]
default_ca      = CA_default            # The default ca section

[ CA_default ]

new_certs_dir   = /.lego/certificates   # default place for new certs.
certificate     = /usr/local/share/ca-certificates/whitedonkey.crt
private_key     = /keys/ca_key.pem

# Honor extensions requested of us
copy_extensions	= copy

# Extensions to add to a CRL. Note: Netscape communicator chokes on V2 CRLs
# so this is commented out by default to leave a V1 CRL.
# crlnumber must also be commented out to leave a V1 CRL.
#crl_extensions        = crl_ext
default_days    = 3650                  # how long to certify for
default_crl_days= 30                    # how long before next CRL
default_md      = sha256                # which md to use.
preserve        = no                    # keep passed DN ordering

[ v3_ca ]
basicConstraints = critical,CA:TRUE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always

[ req ]
default_bits		    = 2048
default_md		        = sha256
#default_keyfile 	    = ${domain}.key      # maybe this is specifying an existing key for CSR?
default_keyfile 	    = admin.whitedonkey.local.key      # maybe this is specifying an existing key for CSR?
distinguished_name      = req_distinguished_name # where to get DN for reqs
attributes              = req_attributes         # req attributes
req_extensions		    = req_ext # The extensions to add to req's
x509_extensions = v3_ca
prompt                  = no

[ req_distinguished_name ]
countryName			    = NZ
stateOrProvinceName		= Auckland
localityName			= Auckland
0.organizationName		= White Donkey Ltd
#commonName			    = ${domain}
commonName			    = admin.whitedonkey.local
emailAddress			= tao.li.7019@gmail.com

[ req_attributes ]
#challengePassword		= A challenge password
#challengePassword_min  = 4
#challengePassword_max	= 20

[ req_ext ]
basicConstraints = critical,CA:TRUE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName          = @alt_names

[alt_names]
#DNS.1 = ${domain}
DNS.1 = admin.whitedonkey.local