# If we use the docker resolver, and upstreams as variables, extra_hosts would never resolve.
resolver 127.0.0.11 valid=30s;

server {
  listen 8083;
  client_max_body_size 30m;

  location / {
    proxy_pass http://storefront:3000;
  }

  location /assets/ {
    proxy_pass http://storefront:3000/assets/;
  }

  location /api/ {
    proxy_pass http://storefront-api:8080;
    proxy_set_header Host $host;
  }

  location /img/ {
    deny all;
  }

  gzip on;
  gzip_proxied any;
  gzip_types
  text/css
  text/javascript
  text/xml
  application/javascript
  application/json
  text/json;
}
