#Here we set the resolver to Docker's internal resolver to allow us setting upstreams as variables
resolver 127.0.0.11 valid=30s;

limit_req_zone $binary_remote_addr zone=publicratelimit:10m rate=3r/s;

access_log  off;
error_log off;

fastcgi_hide_header X-Powered-By;
proxy_hide_header X-Powered-By;
