#@wdca kibana.whitedonkey.local

server {
    set $fastcgi_kibana http://magento2:8082;
    server_name kibana.whitedonkey.local;

    listen 80;
    listen 443 ssl;
    ssl_certificate     /.lego/certificates/kibana.whitedonkey.local.crt;
    ssl_certificate_key /.lego/certificates/kibana.whitedonkey.local.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    location / {
        proxy_pass $fastcgi_kibana;
        proxy_set_header Host $host;
    }
}