#@wdca admin.whitedonkey.local

server {
  set $fastcgi_magento2 http://magento2:8081;
  server_name admin.whitedonkey.local;

  listen 80;
  listen 443 ssl;
  ssl_certificate     /.lego/certificates/admin.whitedonkey.local.crt;
  ssl_certificate_key /.lego/certificates/admin.whitedonkey.local.key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

  location = / {
    return 301 https://admin.whitedonkey.local/mage;
  }

  location / {
    proxy_pass $fastcgi_magento2;
    proxy_set_header Host $host;
  }
}