#@wdca www.whitedonkey.local

server {
    set $fastcgi_storefront http://magento2:8083;
    server_name www.whitedonkey.local;

    listen 80;
    listen 443 ssl;
    ssl_certificate     /.lego/certificates/www.whitedonkey.local.crt;
    ssl_certificate_key /.lego/certificates/www.whitedonkey.local.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    location / {
        proxy_pass $fastcgi_storefront;
        proxy_set_header Host $host;
    }
}