zend_extension=xdebug.so
xdebug.default_enable = 0
xdebug.remote_autostart = 0
xdebug.remote_enable = 1
xdebug.remote_handler = dbgp

; port 9000 is used by php-fpm
xdebug.remote_port=9000
; xdebug.remote_autostart=1

; no need for remote host
xdebug.remote_connect_back true
xdebug.idekey="PHPSTORM"
xdebug.remote_host=dockerhost


; xdebug.auto_trace=1
xdebug.trace_output_dir=/magento2/var/report/segmentation/

xdebug.profiler_enable=０
xdebug.profiler_enable_trigger=1
xdebug.profiler_append=1
xdebug.profiler_output_dir=/magento2/var/report
xdebug.profiler_output_name = callgrind.out.%t.%s
